// <auto-generated />
namespace Mail_Sender.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class M61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M61));
        
        string IMigrationMetadata.Id
        {
            get { return "201901261559170_M61"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
